[project]
name = "myproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "flask-pydantic>=0.13.1",
    "pydantic>=2.11.7",
    "yfinance>=0.2.65",
]
